import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function AppForm() {
  return (
    <div className={styles.container}>
      <Head>
        <title>症状選択</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          症状選択
        </h1>

        <p className={styles.description}>
          当てはまる症状を選択してください。
        </p>

        <label><input type="radio" name="q3" value="はい"/>頭痛</label>
        <label><input type="radio" name="q3" value="はい"/>頭痛</label>
        <label><input type="radio" name="q3" value="はい"/>頭痛</label>
        
        <ul>
          <li>
            <label><input type="radio" name="q3" value="はい"/>頭痛</label>
          </li>
          <li>
            <label><input type="radio" name="q3" value="はい"/>頭痛</label>
          </li>
          <li>
            <label><input type="radio" name="q3" value="はい"/>頭痛</label>
          </li>
          <li>
            <label><input type="radio" name="q3" value="はい"/>頭痛</label>
          </li>
        </ul>
      </main>

      <footer className={styles.footer}>Powered by Aoba</footer>
    </div>
  );
} 