import Head from "next/head";
import stylesForm from "../styles/form.module.css";
import styles from "../styles/Home.module.css";

export default function AppForm() {

  const Headache = [
    {symptop:'熱もある', tag:'headache1'},
    {symptop:'頭が重い', tag:'headache2'},
    {symptop:'頭がズキズキする', tag:'headache3'},
  ]

  const Fever = [
    {symptop:'とにかく熱がひどい', tag:'fever1'},
    {symptop:'頭痛・喉の痛みがする', tag:'fever2'},
    {symptop:'くしゃみ・鼻水が止まらない', tag:'fever3'},
  ]

  const StomachAche = [
    {symptop:'胃がキリキリする', tag:'stomach'},
    {symptop:'お腹の調子が悪い', tag:'colon1'},
    {symptop:'下痢がする', tag:'colon2'},
  ]

  const Menstruation = [
    {symptop:'生理痛', tag:'cramp'},
  ]

  const FirstStage = [
    {symptop:'頭痛', secondStage:Headache},
    {symptop:'熱', secondStage:Fever},
    {symptop:'胃痛・腹痛', secondStage:StomachAche},
    {symptop:'生理痛', secondStage:Menstruation},
  ]

  return (
    <div>
      <Head>
        <title>症状選択</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css" />
      </Head>

      <section className="hero">
        <div className="hero-body">
          <div clasclassNames="container">
            <span className="has-text-centeredr">
              Medivery
            </span>
          </div>
        </div>
      </section>

      <main className="container">
        <h1 className="title">症状選択</h1>
        <p>当てはまる症状を選択してください。</p>

        <div className="section">
          <h2>症状選択(第一段階)</h2>
          <ul>
            {FirstStage.map((value) => (
              <li><label><input type="radio" name="q1" value={value.symptop}/>{value.symptop}</label></li>
            ))}
          </ul>
        </div>

        <div className="section">
          <h2>症状選択(第二段階)</h2>
          <ul>
            {Headache.map((value) => (
              <li className="decorarion-none"><label><input type="radio" name="q2" value={value.tag}/>{value.symptop}</label></li>
            ))}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}>Powered by Aoba</footer>
    </div>
  );
} 